baseURL = "https://sc-mallorca.com"
title = "SC Mallorca"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Mallorca Software Crafters" # title for frontpage, may include image
copyright = "Pere Picó"
description = 'As aspiring Software Crafters </br> we are raising the bar of professional software development</br>by practicing it and helping others learn the craft'
startbuttonText = "Join us"
startbuttonLink = "https://www.meetup.com/es-ES/mallorca-software-crafters/"
body_is_markdown = true

[[params.menu.main]]
url = '/'
title = "Home"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Our manifesto'
body = '''
Not only working software, but also well-crafted software.

Not only responding to change, but also steadily adding value.

Not only individuals and interactions, but also a community of professionals.

Not only customer collaboration, but also productive partnerships.
'''

[[params.one.icon]]
icon = "fa-code"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-truck"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-user"
style = "3"
label = "Dolor"

[[params.one.icon]]
icon = "fa-handshake-o"
style = "3"
label = "Dolor"

[params.two]
enable = false

[params.three]
enable = false

[params.cta]
enable = true
title = "Join the community!"
body = "We are software engineers who strive to be true crafters in their work."

[[params.cta.link]]
href = "https://www.meetup.com/es-ES/mallorca-software-crafters/?action=join"
text = "Join us"
special = true

[[params.cta.link]]
href = "https://twitter.com/scmallorca"
text = "Follow us"
special = false

[params.contact]
enable = false

[params.social]
twitter = "scmallorca"

# language specific options

[languages.en]
weight = 0
languageName = "English"
